version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          BUNDLE_PATH: vendor/bundle

    steps:
      - checkout
      - run:
          name: Install rspec
          command: gem install rspec rspec_junit_formatter
#      - run:
#          name: Which Bundler?
#          command: bundle -v
#      - restore_cache:
#          keys:
#            - adventofcode2019-{{ checksum "Gemfile.lock" }}
#            - adventofcode2019-
#      - run:
#          name: Bundle Install
#          command: bundle check --path vendor/bundle || bundle install
#
#      - save_cache:
#          key: adventofcode2019-{{ checksum "Gemfile.lock" }}
#          paths:
#            - vendor/bundle
      - run:
          name: Run Tests
          command: rspec --format RspecJunitFormatter --out test_results/rspec.xml
      - store_test_results:
          path: test_results